Задание по разметке
htmlacademy-htmlcss/1239257-device-33 pull request #2
Opened 2022-01-24 07:48 UTC by miramar88

2022-01-24 19:36 UTC, ego-o requested changes
Пока что ты справилась лучше всех) Меньше всего замечаний) Так держать)

2022-01-24 19:36 UTC, saranchyev commented on index.html
> +          <img class="slider-item-photo" src="" alt="Квадрокоптер">
Тесттовое описание картинок в alt так же должно заканичваться на точку. Нужно перепроверить это у всех изображений на обеих страницах
https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01

2022-01-24 19:36 UTC, saranchyev commented on index.html
> +    <h1 class="visually-hidden">Интернет-магазин Device</h1>
Текст в скрытых контейнерах должен заканчиваться на точку. Необходимо перепроверить все такие элементы на обеих страницах
https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-02

2022-01-24 19:36 UTC, saranchyev commented on index.html
> +          </button>
Кнопка тут как я понимаю это плюсик на макете https://skr.sh/sCAODG85HwS

Если так, то лучше будет без неё. Это скорее декоративная инконка, чем кнопка. И текст и плюсик действуют как единое целое - при наведении на текст плюсик меняет цвет. И при клике на текст, и при клике на кнопку открывается одно и то же меню. Дак зачем нам два интерактивных элемента, делающих то же самое?

2022-01-24 19:36 UTC, ego-o commented on index.html
> +    <a href="tel:+78128121212" class="footer-phone">Тел.: +7 (812) 812-12-12</a>
Аттрибут class должен идти первым. Это нужно перепроверить у всех элементов на всех страницах
https://up.htmlacademy.ru/htmlcss/33/criteries#PROJ-01
http://codeguide.academy/html-css.html#html-attr-order

2022-01-24 19:36 UTC, ego-o commented on index.html
> +Логотип .html academy ведёт на главную страницу сайта разработчика — https://htmlacademy.ru/
Это, наверное, лишнее)

2022-01-24 19:36 UTC, ego-o commented on catalog.html
> +      <h3 class="goods-sort">Сортировка</h3>
Думаю, что сортировку стоит вынести в отдельный блок, как то она не подходит к списку товаров тут, словно сортировка тоже товар

2022-01-24 19:36 UTC, ego-o commented on catalog.html
> +        </li>
Думаю, тут лучше вынести кнопки вперед и назад за список, а са список сделать маркированным. Мы делаем вначале разметку, а только потом пишем стили для того, чтобы убедиться, что и без стилей (если они не загрузятся), сама страница останется читаемой, просто будет выглядеть как документ MS Word. Сейчас в таком варианте пагинация смотрится несколько странно - нумерованный список, с цифрами внутри - https://skr.sh/sCAQ9hBQ4Ad

2022-01-24 19:36 UTC, ego-o commented on catalog.html
> +      <input class="header-search-field" type="text" name="search-field" placeholder="Текст поиска" id="">
id не может быть пустым. Нет связанного с ипутом label или аттрибута aria-label

2022-01-24 19:36 UTC, ego-o commented on index.html
> +      <input class="header-search-field" type="text" name="search-field" placeholder="Текст поиска">
Нет связанного с инпутом label или аттрибута aria-label

2022-01-24 19:36 UTC, ego-o commented on index.html
> +        <input class="subscribe-input" type="email" name="subscribe-email" id="user-subscribe" placeholder="Ваш e-mail"
Нет связанного с инпутом label или аттрибута aria-label

2022-01-24 19:36 UTC, ego-o commented on catalog.html
> +      </select>
Нет связанного с селектом label или аттрибута aria-label

2022-01-25 11:40 UTC, miramar88 commented on catalog.html
> +      <input class="header-search-field" type="text" name="search-field" placeholder="Текст поиска" id="">
Можно ли здесь сделать type="search"?

2022-01-25 11:43 UTC, miramar88 commented on index.html
> +      <input class="header-search-field" type="text" name="search-field" placeholder="Текст поиска">
Получается, label или aria-label нужно добавлять в любом случае? Здесь, наверно, лучше aria-label, потому что он будет сразу скрыт?

2022-01-25 14:57 UTC, ego-o commented on catalog.html
> +      <input class="header-search-field" type="text" name="search-field" placeholder="Текст поиска" id="">
Да, почему нет

2022-01-25 14:59 UTC, ego-o commented on index.html
> +      <input class="header-search-field" type="text" name="search-field" placeholder="Текст поиска">
Ну, я бы тоже добавил aria-label. Подпись у поля ввода в целом имеется, так что и без label будет понятно

2022-01-26 22:27 UTC, ego-o requested changes
Почти все хорошо) Остались совсем небольшие правки. Давай их дофиксим и задание принимаю

2022-01-26 22:27 UTC, ego-o commented on catalog.html
> +        <option value="popular" aria-label="Сначала популярные.">популярные</option>
Для селекта все равно нужен label, который опишет, а что собтвенно мы в нем выбираем. А для option атрибут aria-label не очень нужен, так как они и так имеют текстовое описние

2022-01-27 06:41 UTC, merged