Декор главной страницы
htmlacademy-htmlcss/1239257-device-33 pull request #8
Opened 2022-03-03 10:07 UTC by miramar88

2022-03-03 18:39 UTC, ego-o requested changes

2022-03-03 18:39 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/vCme0sUtzZ8
https://skr.sh/vCmMy1NK55g
Необходимо доработать страницы по ПП

2022-03-03 18:39 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/vCmsK1y4x4e
https://skr.sh/sCmFR0lwOZz
Нужно доработать стили для фокуса в шапке у основного меню. У каталога товаров нужно добавить иконку плюса

2022-03-03 18:39 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/sCmw8UbGs75
https://skr.sh/sCmegWkCxoF
Не проработаны стили на наведение, фокус, клик у стрелок  переключения слайдов

2022-03-03 18:39 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/sCmeWEvADrQ
https://skr.sh/sCmTIRF5pq9
При фокусе на точках-переключателях слайдов - обводка должна быть квадратной и с отступами внутри

2022-03-03 18:39 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/sCmfBP65lA3
Нужно добавить закругленные края полю поиска

2022-03-03 18:39 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/vCm3OvvhDYV
https://skr.sh/sCmVKmALnyK
При клике по категории каталога текст тоже должен быть прозрачным

2022-03-03 18:39 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/vCmYHkpuqGN
https://skr.sh/sCmECDTQtvu
При клике текст должен быть желтого цвета, сейчас белого

2022-03-03 18:39 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/vCmZGfKrs8s
Если во время клика отвести мышку в сторону, то можно наблюдать странный артефакт у кнопки (поверх желтого фона появляется светло-желтая полоска)

2022-03-03 18:39 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/vCm67DzK5vG
https://skr.sh/sCmaI4lJBnI
При наведении на карточку товара прозрачной должны становится и изображение и текст. Карточка товара должна целиком являться одной ссылкой, не должно быть отдельно ссылки у изображения, и отдельно ссылки у текста

2022-03-03 18:39 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/vCmmpKmO15g
Если во время клика по кнопке отвести мышку в сторону, то у неё пропадает фоновый цвет

2022-03-03 18:39 UTC, ego-o commented on catalog.html
> +                  d="M6 .39H4v12h2v-12ZM2 4.39H0v8h2v-8ZM10 3.39H8v9h2v-9Z" />
теги у svg иконок можно не разбивать по строкам, а все поместить в одну строчку, так как они вряд-ли кем то будут редактироваться вручную. Это сэкономит уровни вложенности тегов и читать разметку станет проще

2022-03-03 18:39 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/sCmVxOEGIZT
Для кнопки не проработан disabled стиль

2022-03-05 07:46 UTC, miramar88 commented on catalog.html
> +                  d="M6 .39H4v12h2v-12ZM2 4.39H0v8h2v-8ZM10 3.39H8v9h2v-9Z" />
VScode почему-то разбивает их на строки автоматически при сохранении. У меня раньше стоял плагин, который все выравнивал, теперь он отключен. Может быть, надо поправить настройки самого редактора?

2022-03-07 05:35 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/sCqGFQM0uuP
Нужно еще доработать такой момент, чтобы нижняя часть рамки фокуса не скрывалась под фоном следующего блока. Для этого нужно добавить отступ от нижней границы шапки, чтобы шапка была чуть больше (до: https://skr.sh/sCqnLP7xbCT / после: https://skr.sh/sCqZLJbOxt7), а у элементов слайдера чуть уменьшить отступ сверху, чтобы они совпадали с ПП

2022-03-07 06:14 UTC, ego-o requested changes

2022-03-07 06:14 UTC, saranchyev commented on catalog.html
> +              Корзина
https://skr.sh/sCqPKJkxJ7U
https://skr.sh/sCqmv2W6lDI
При фокусе белый кругляш с цифрой тоже должен быть внутри рамки

2022-03-07 06:14 UTC, saranchyev commented on catalog.html
> +                <span class="goods-list-overlay button">Подробнее</span>
https://skr.sh/vCqjPhHKMlu
В карточке товара, при наведении появляется псевдо-кнопка. Она не должна иметь никакого действия, это не ссылка, она просто должна быть. На ней нельзя сфокусироваться, но она должна так же менять внешний вид при наведении - https://skr.sh/vCqmgDPb2Ni

2022-03-07 06:14 UTC, saranchyev commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/vCqCu61uNZN
При наведении на отключенную кнопку она никак не должна реагировать

2022-03-07 06:14 UTC, ego-o commented on catalog.html
> +          <svg class="header-search-icon" width="16" height="17" viewBox="0 0 16 17" aria-hidden="true"
https://skr.sh/sCqiLLYz7fT
На странице каталога нужно доработать стили у формы поиска

2022-03-07 06:14 UTC, ego-o commented on catalog.html
> +            <a class="header-navigation-link header-navigation-link-current" href="#">Каталог товаров</a>
https://skr.sh/vCqgHTglbO8
При наведении на каталог иконка с плюсом так же должна менять и цвет

2022-03-07 06:14 UTC, ego-o commented on catalog.html
> +                </div>
https://skr.sh/vCqE6d3epJO
Еще сейчас глянул прототип в фигме, на нём у кнопки загрузить еще другие стили для наведения и клика. В стайлгайде второй стиль для кнопки с черным фоном используется только в кнопке "подписаться". Это ошибка с текстом в макете, потом поправят её

2022-03-10 14:50 UTC, ego-o commented on catalog.html
> +                <span class="goods-list-overlay button">Подробнее</span>
Не поправлено

2022-03-10 14:57 UTC, merged